### ISSUE TITLE
Add default values to string/1, confirm/1 and choose/2 functions

### ISSUE THREAD

**Issue by rzcastilho** [behind-design/ex_prompt#2]
Add the possibility to pass default values when asking for something. When the user press ENTER, the default value is returned.

Keeps the previous behavior if no default value is informed.

Examples:

* **string/2**

  ```elixir
  iex> ExPrompt.string("What is the hostname?", "localhost")
  (localhost) What is the hostname? 
  "localhost"
  ```

* **confirm/2**

  ```elixir
  iex> ExPrompt.confirm("Are you sure you want to delete this file?", false)
  Are you sure you want to delete this file? [yN] 
  false
  ```

* **choose/3**

  ```elixir
  iex> ExPrompt.choose("Favorite color?" , ~w(red green blue), 2)
  
    1) red
    2) green
    3) blue
  
  Favorite color? (green) 
  1
  ```

**Comment by bjufre** [comment]
@rzcastilho sounds good and sensible! I will take a look at it as soon as I can this week. And will take the opportunity to update any dependencies and such just to make sure that everything works with the latest language version.

**Comment by rzcastilho** [comment]
@bjufre  I can send you a PR with these changes if you agree.

**Comment by bjufre** [comment]
@rzcastilho sure go ahead! I will review asap this week 👌

**Comment by bjufre** [comment]
@rzcastilho I kinda started, but only got as far as updating the deps and elixir version. But nothing regarding the functionality. Feel free to do the PR and I can then update deps and Elixir version myself 💪
